### ISSUE TITLE
@ColumnName annotations not being respected

### ISSUE THREAD

**Issue by omnipitous** [Manikandan-K/jdbi-folder#4]
In-general this library works great and saved me a bunch of code to write, Thanks. I did just run into an issue with the hydration of my domain objects by the CustomMapperFactory: I have ubiquitously annotated all of the fields in my domain objects with @ColumnName("stuff") annotations and was experiencing a case where 2 of my columns were failing to hydrate (always coming through as NULL). The 2 columns specifically are Booleans stored in the database as an integer value 1 or 0 SO as far as jDBI and the Folder are concerned they are just Integer values (I interpret them as Boolean elsewhere) BUT given their nature I named the fields a bit different than the natural camel-case naming would be. I spent a lot of time triple checking all of the various Strings to make sure I didn't have any typos / etc and finally, on a guess, renamed the columns to be their "typical" camel case conversion and that fixed the problem.  Here's what the fields in question look like:

// Didn't work... always NULL.
    @ColumnName("IS_REPEATABLE")
    private Integer repeatable;
    @ColumnName("IS_MANDATORY")
    private Integer mandatory;

// Successfully pulled values from DB queries.
    @ColumnName("IS_REPEATABLE")
    private Integer isRepeatable;
    @ColumnName("IS_MANDATORY")
    private Integer isMandatory;

As listed, these fields were originally named "repeatable" and "mandatory". Changing them to "isRepeatable" and "isMandatory" and changing their getters' naming to match caused them to successfully hydrate SO my presumption is that the annotations are being ignored. All of my other columns are working correctly but they were all already named the camel case equivalent of their columns so the annotations were redundant. Thanks

PS. For some reason GitHub is flattening the annotations in my issue description. FYI They are correctly cased "ColumnName" (capital C and N) even if it doesn't appear as such in the text above.

**Comment by Manikandan-K** [comment]
Could you share your query as well ?

**Comment by omnipitous** [comment]
Well.. Here's the full query which joins a LOT of tables.. It includes actually 4 of these boolean-like fields.. with "primary" and "restricted" in the "groupType" fold in addition to the above that are in the "restrict" fold. The query pasted below is specifically reverted to when it was NOT working..  (Reflecting the "Didn't work... always NULL." section described above):

SELECT DISTINCT a.*,
g.ATTR_GROUP_ID AS groups$attrGroupId,
g.GROUP_NAME AS groups$groupName,
g.DESCRIPTION AS groups$description,
g.ATTR_GROUP_TYPE_ID AS groups$attrGroupTypeId,
g.ORDER_WEIGHT AS groups$orderWeight,
g.CREATED_DATE AS groups$createdDate,
g.CREATED_BY AS groups$createdBy,
g.MODIFIED_DATE AS groups$modifiedDate,
g.MODIFIED_BY AS groups$modifiedBy,
gt.ATTR_GROUP_TYPE_ID AS groupType$attrGroupTypeId,
gt.GROUP_TYPE_NAME AS groupType$groupTypeName,
gt.IS_PRIMARY AS groupType$primary,
gt.IS_RESTRICTED AS groupType$restricted,
d.ATTR_DATATYPE_ID AS datatype$attrDatatypeId,
d.DATATYPE_NAME AS datatype$datatypeName,
s.ATTR_STORAGE_ID AS storage$attrStorageId,
s.STORAGE_NAME AS storage$storageName,
r.ATTR_ROUND_ID AS round$attrRoundId,
r.ROUND_NAME AS round$roundName,
r.STATUS AS round$status,
r.COMMENTS AS round$comments,
r.CREATED_DATE AS round$createdDate,
r.CREATED_BY AS round$createdBy,
r.MODIFIED_DATE AS round$modifiedDate,
r.MODIFIED_BY AS round$modifiedBy,
r.APPROVED_DATE AS round$approvedDate,
r.APPROVED_BY AS round$approvedBy,
r.COMMITTED_DATE AS round$committedDate,
r.COMMITTED_BY AS round$committedBy,
rx.ATTR_RESTRICT_ID AS restrict$attrRestrictId,
rx.ATTRIBUTE_ID AS restrict$attributeId,
rx.VENDORID AS restrict$vendorId,
rx.RETAILERID AS restrict$retailerId,
rx.IS_MANDATORY AS restrict$mandatory,
rx.IS_REPEATABLE AS restrict$repeatable,
rx.INITIAL_REPEAT_LABEL AS restrict$initialRepeatLabel,
rx.FIRST_REPEAT_VAL AS restrict$firstRepeatVal,
rx.MAX_LENGTH AS restrict$maxLength,
rx.CREATED_DATE AS restrict$createdDate,
rx.CREATED_BY AS restrict$createdBy,
rx.MODIFIED_DATE AS restrict$modifiedDate,
rx.MODIFIED_BY AS restrict$modifiedBy,
t.ATTR_TRANSFORM_ID AS transform$attrTransformId,
t.ATTRIBUTE_ID AS transform$attributeId,
t.VENDORID AS transform$vendorId,
t.RETAILERID AS transform$retailerId,
t.TRANSFORMATION_RULE AS transform$transformationRule,
t.CREATED_DATE AS transform$createdDate,
t.CREATED_BY AS transform$createdBy,
t.MODIFIED_DATE AS transform$modifiedDate,
t.MODIFIED_BY AS transform$modifiedBy,
v.ATTR_VALID_ID AS valid$attrValidId,
v.ATTRIBUTE_ID AS valid$attributeId,
v.VENDORID AS valid$vendorId,
v.RETAILERID AS valid$retailerId,
v.VALIDATION_RULE AS valid$validationRule,
v.CREATED_DATE AS valid$createdDate,
v.CREATED_BY AS valid$createdBy,
v.MODIFIED_DATE AS valid$modifiedDate,
v.MODIFIED_BY AS valid$modifiedBy,
vx.ATTR_VALUE_ID AS value$attrValueId,
vx.ATTRIBUTE_ID AS value$attributeId,
vx.VENDORID AS value$vendorId,
vx.RETAILERID AS value$retailerId,
vx.ATTR_KEY_PAIR AS value$attrKeyPair,
vx.VALUE AS value$value,
vx.CREATED_DATE AS value$createdDate,
vx.CREATED_BY AS value$createdBy,
vx.MODIFIED_DATE AS value$modifiedDate,
vx.MODIFIED_BY AS value$modifiedBy,
ax.ATTR_ALIAS_ID AS alias$attrAliasId,
ax.ATTRIBUTE_ID AS alias$attributeId,
ax.ALIAS_NAME AS alias$aliasName,
ax.DISPLAY_NAME AS alias$displayName,
ax.CREATED_DATE AS alias$createdDate,
ax.CREATED_BY AS alias$createdBy,
ax.MODIFIED_DATE AS alias$modifiedDate,
ax.MODIFIED_BY AS alias$modifiedBy
FROM ATTRREG.ATTRIBUTE a
LEFT JOIN ATTRREG.ATTR_JOIN_GROUP jg ON jg.ATTR_GROUP_ID = a.ATTR_GROUP_ID
  OR jg.ATTRIBUTE_ID = a.ATTRIBUTE_ID OR jg.ATTRIBUTE_ID = a.PARENT_ATTRIBUTE_ID
LEFT JOIN ATTRREG.ATTR_GROUP g ON g.ATTR_GROUP_ID = a.ATTR_GROUP_ID
  OR g.ATTR_GROUP_ID = jg.PARENT_GROUP_ID
LEFT JOIN ATTRREG.ATTR_GROUP_TYPE gt ON gt.ATTR_GROUP_TYPE_ID = g.ATTR_GROUP_TYPE_ID
LEFT JOIN ATTRREG.ATTR_DATATYPE d ON d.ATTR_DATATYPE_ID = a.ATTR_DATATYPE_ID
LEFT JOIN ATTRREG.ATTR_STORAGE s ON s.ATTR_STORAGE_ID = a.ATTR_STORAGE_ID
LEFT JOIN ATTRREG.ATTR_ROUND r ON r.ATTR_ROUND_ID = a.ATTR_ROUND_ID
LEFT JOIN ATTRREG.ATTR_RESTRICT rx ON rx.ATTRIBUTE_ID = a.ATTRIBUTE_ID
LEFT JOIN ATTRREG.ATTR_TRANSFORM t ON t.ATTRIBUTE_ID = a.ATTRIBUTE_ID
LEFT JOIN ATTRREG.ATTR_VALID v ON v.ATTRIBUTE_ID = a.ATTRIBUTE_ID
LEFT JOIN ATTRREG.ATTR_VALUE vx ON vx.ATTRIBUTE_ID = a.ATTRIBUTE_ID
LEFT JOIN ATTRREG.ATTR_ALIAS ax ON ax.ATTRIBUTE_ID = a.ATTRIBUTE_ID

All 4 fields work fine when the fields repeatable, mandatory, primary and restricted are renamed to isRepeatable, isMandatory, isPrimary and isRestricted as described in the OP.

**Comment by Manikandan-K** [comment]
Thanks for sharing the query. I think there is slight misunderstanding about ColumnName Annotation due to lack of documentation. ColumnName annotation value used to match the column name of the table if we don't specify the alias for the column name. If we specify the column name, we should have alias name and Column name annotation value should be same. In your case,

    rx.IS_MANDATORY AS restrict$mandatory,
    rx.IS_REPEATABLE AS restrict$repeatable,

database column value IS_MANDATORY is overridden by the alias name ```mandatory  (restrict$mandatory)```. So ColumnName annotation should have mandatory value. 

There are two option to solve your problem. Change your alias to match ColumnName annotation value.

    rx.IS_MANDATORY AS restrict$IS_MANDATORY,
    rx.IS_REPEATABLE AS restrict$IS_REPEATABLE,

But I would recommend removing ColumnName annotation and make alias name and field name match.

ColumnName annotation is introduces for different purpose.  When you've different name in database and java object, everytime when you write a query against the table you've alias the column name to object name. To avoid, this annotation is introduced. If you're going to alias the column in the query, I dont see need for the ColumnName annotation itself. Just use field value in java object as alias in the query.

Hope this helps.
